Repository INFLUY/Influy-BE, pull requests merged in 2025-05, with the labels that each got.

#6 #5 feat : 도메인 세팅
  src/main/java/com/influy/domain/announcement/domain/Announcement.java
  src/main/java/com/influy/domain/answer/domain/Answer.java
  src/main/java/com/influy/domain/answerCard/domain/AnswerCard.java
  src/main/java/com/influy/domain/image/domain/Image.java
  src/main/java/com/influy/domain/item/domain/Item.java
  src/main/java/com/influy/domain/item/domain/ItemStatus.java
  src/main/java/com/influy/domain/itemCategory/domain/ItemCategory.java
  src/main/java/com/influy/domain/profileLink/domain/ProfileLink.java
  src/main/java/com/influy/domain/profileLink/domain/ProfileLinkType.java
  src/main/java/com/influy/domain/question/domain/Question.java
  src/main/java/com/influy/domain/questionCategory/domain/QuestionCategory.java
  src/main/java/com/influy/domain/seller/domain/Seller.java
  src/main/java/com/influy/domain/temp/controller/TempController.java
  src/main/java/com/influy/domain/user/domain/User.java
Labels: ✨ Feature

#9 #7 Deploy: CI/CD 구축
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  docker-compose.yml
Labels: 🌎 Deploy

#13 #12 Deploy: nginx 설정
  .github/workflows/deploy.yml
  Dockerfile
  docker-compose.yml
  src/main/java/com/influy/domain/faqCategory/entity/FaqCategory.java
  src/main/java/com/influy/domain/questionCategory/entity/QuestionCategory.java
Labels: 🌎 Deploy

#18 #14 Seller/profile 관련 API 구현 2 + develop 리셋
  build.gradle
  src/main/java/com/influy/domain/profileLink/converter/ProfileLinkConverter.java
  src/main/java/com/influy/domain/profileLink/entity/ProfileLink.java
  src/main/java/com/influy/domain/profileLink/entity/ProfileLinkType.java
  src/main/java/com/influy/domain/profileLink/repository/ProfileLinkRepository.java
  src/main/java/com/influy/domain/profileLink/service/ProfileLinkService.java
  src/main/java/com/influy/domain/seller/controller/SellerController.java
  src/main/java/com/influy/domain/seller/converter/SellerConverter.java
  src/main/java/com/influy/domain/seller/dto/SellerRequestDTO.java
  src/main/java/com/influy/domain/seller/dto/SellerResponseDTO.java
  src/main/java/com/influy/domain/seller/entity/Seller.java
  src/main/java/com/influy/domain/seller/repository/SellerRepository.java
  src/main/java/com/influy/domain/seller/service/SellerService.java
  src/main/java/com/influy/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#23 #21 Cors 정상 작동 확인
  src/main/java/com/influy/global/config/CorsConfig.java
  src/main/java/com/influy/global/config/SecurityConfig.java
Labels: 𐃏 Setting

#28 #17 셀러 공지 관련 API 구현
  src/main/java/com/influy/domain/announcement/controller/AnnouncementController.java
  src/main/java/com/influy/domain/announcement/converter/AnnouncementConverter.java
  src/main/java/com/influy/domain/announcement/dto/AnnouncementRequestDTO.java
  src/main/java/com/influy/domain/announcement/dto/AnnouncementResponseDTO.java
  src/main/java/com/influy/domain/announcement/entity/Announcement.java
  src/main/java/com/influy/domain/announcement/repository/AnnouncementRepository.java
  src/main/java/com/influy/domain/announcement/service/AnnouncementService.java
  src/main/java/com/influy/domain/seller/entity/Seller.java
  src/main/java/com/influy/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#33 #17 refactor : 부하 테스트 용 수정
  src/main/java/com/influy/domain/announcement/controller/AnnouncementController.java
  src/main/java/com/influy/domain/announcement/dto/AnnouncementResponseDTO.java
Labels: 🛠️ Refactor

#29 #21 셀러 링크 인 바이오 관련 API 구현
  src/main/java/com/influy/domain/profileLink/controller/ProfileLinkController.java
  src/main/java/com/influy/domain/profileLink/converter/ProfileLinkConverter.java
  src/main/java/com/influy/domain/profileLink/dto/ProfileLinkRequestDTO.java
  src/main/java/com/influy/domain/profileLink/dto/ProfileLinkResponseDTO.java
  src/main/java/com/influy/domain/profileLink/entity/ProfileLink.java
  src/main/java/com/influy/domain/profileLink/repository/ProfileLinkRepository.java
  src/main/java/com/influy/domain/profileLink/service/ProfileLinkService.java
  src/main/java/com/influy/domain/profileLink/service/ProfileLinkServiceImpl.java
  src/main/java/com/influy/domain/seller/controller/SellerController.java
  src/main/java/com/influy/domain/seller/entity/Seller.java
  src/main/java/com/influy/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature

#30 #24 셀러 FaqCategory CRUD API 구현
  src/main/java/com/influy/domain/faqCategory/controller/FaqRestController.java
  src/main/java/com/influy/domain/faqCategory/converter/FaqCategoryConverter.java
  src/main/java/com/influy/domain/faqCategory/dto/FaqCategoryRequestDto.java
  src/main/java/com/influy/domain/faqCategory/dto/FaqCategoryResponseDto.java
  src/main/java/com/influy/domain/faqCategory/entity/FaqCategory.java
  src/main/java/com/influy/domain/faqCategory/repository/FaqCategoryRepository.java
  src/main/java/com/influy/domain/faqCategory/service/FaqCategoryService.java
  src/main/java/com/influy/domain/faqCategory/service/FaqCategoryServiceImpl.java
  src/main/java/com/influy/domain/item/entity/Item.java
  src/main/java/com/influy/domain/item/service/ItemServiceImpl.java
  src/main/java/com/influy/global/apiPayload/code/status/ErrorStatus.java
Labels: ✨ Feature
