Repository INFLUY/Influy-BE, pull requests merged in 2025-08, with the labels that each got.

#101 질문 창구+닉네임 8자 로직 추가
  src/main/java/com/influy/domain/home/converter/HomeConverter.java
  src/main/java/com/influy/domain/home/dto/HomeResponseDto.java
  src/main/java/com/influy/domain/home/service/HomeServiceImpl.java
  src/main/java/com/influy/domain/item/repository/ItemRepository.java
  src/main/java/com/influy/domain/member/converter/MemberConverter.java
Labels: 🛠️ Refactor

#100 Seller/profile 업데이트 시 기능 추가
  src/main/java/com/influy/domain/member/entity/Member.java
  src/main/java/com/influy/domain/sellerProfile/entity/SellerProfile.java
Labels: ✨ Feature

#105 #64 Refactor: 아이템 조회 관련 수정
  src/main/java/com/influy/domain/image/service/ImageService.java
  src/main/java/com/influy/domain/image/service/ImageServiceImpl.java
  src/main/java/com/influy/domain/item/controller/ItemRestController.java
  src/main/java/com/influy/domain/item/converter/ItemConverter.java
  src/main/java/com/influy/domain/item/dto/ItemRequestDto.java
  src/main/java/com/influy/domain/item/dto/ItemResponseDto.java
  src/main/java/com/influy/domain/item/entity/Item.java
  src/main/java/com/influy/domain/item/repository/ItemRepository.java
  src/main/java/com/influy/domain/item/service/ItemService.java
  src/main/java/com/influy/domain/item/service/ItemServiceImpl.java
  src/main/java/com/influy/domain/sellerProfile/controller/SellerProfileController.java
  src/main/java/com/influy/domain/sellerProfile/service/SellerProfileService.java
  src/main/java/com/influy/domain/sellerProfile/service/SellerProfileServiceImpl.java
  src/main/java/com/influy/global/apiPayload/code/status/ErrorStatus.java
Labels: 🎨 Fix, ✨ Feature, 🛠️ Refactor

#108 회원 탈퇴, 수정 시 s3 이미지 삭제 로직 추가
  src/main/java/com/influy/domain/item/repository/ItemRepository.java
  src/main/java/com/influy/domain/member/service/MemberServiceImpl.java
  src/main/java/com/influy/domain/sellerProfile/service/SellerProfileServiceImpl.java
Labels: ✨ Feature

#109 #64 Refactor: 아이템 상세 조회 필드 추가
  src/main/java/com/influy/domain/item/converter/ItemConverter.java
  src/main/java/com/influy/domain/item/dto/ItemResponseDto.java
Labels: 🛠️ Refactor

#110 #64 refactor : 공지 리스트 조회 시 최상단 공지를 첫번째로 제공
  src/main/java/com/influy/domain/announcement/repository/AnnouncementRepository.java
  src/main/java/com/influy/domain/announcement/service/AnnouncementServiceImpl.java
Labels: 🛠️ Refactor

#111 #64 Refactor: 셀러 오버뷰 정보 path var 수정
  src/main/java/com/influy/domain/sellerProfile/controller/SellerProfileController.java
Labels: 🎨 Fix, 🛠️ Refactor

#112 #64 Feature: 보관 여부 수정 api 구현
  src/main/java/com/influy/domain/item/controller/ItemRestController.java
  src/main/java/com/influy/domain/item/entity/Item.java
  src/main/java/com/influy/domain/item/service/ItemService.java
  src/main/java/com/influy/domain/item/service/ItemServiceImpl.java
Labels: ✨ Feature

#113 #64 feat : 계정 설정 시 기본 정보 조회 용 api 구현
  src/main/java/com/influy/domain/member/controller/MemberController.java
  src/main/java/com/influy/domain/member/converter/MemberConverter.java
  src/main/java/com/influy/domain/member/dto/MemberResponseDTO.java
  src/main/java/com/influy/domain/member/service/MemberService.java
  src/main/java/com/influy/domain/member/service/MemberServiceImpl.java
  src/main/java/com/influy/domain/sellerProfile/dto/SellerProfileResponseDTO.java
Labels: ✨ Feature

#114 #64 Refactor: query문 수정
  src/main/java/com/influy/domain/item/repository/ItemRepository.java
Labels: 🛠️ Refactor

#117 Refactor: QA중 수정
  src/main/java/com/influy/domain/item/controller/ItemRestController.java
  src/main/java/com/influy/domain/item/converter/ItemConverter.java
  src/main/java/com/influy/domain/item/dto/ItemResponseDto.java
  src/main/java/com/influy/domain/item/repository/ItemRepository.java
  src/main/java/com/influy/domain/item/service/ItemService.java
  src/main/java/com/influy/domain/item/service/ItemServiceImpl.java
  src/main/java/com/influy/global/config/SecurityConfig.java
  src/main/java/com/influy/global/util/StaticValues.java
Labels: 🛠️ Refactor

#118 #64 Refactor: 아이템 관련 응답 수정
  src/main/java/com/influy/domain/item/controller/ItemRestController.java
  src/main/java/com/influy/domain/item/converter/ItemConverter.java
  src/main/java/com/influy/domain/item/dto/ItemResponseDto.java
  src/main/java/com/influy/domain/item/service/ItemServiceImpl.java
  src/main/java/com/influy/domain/question/repository/QuestionRepository.java
Labels: 🎨 Fix, 🛠️ Refactor

#121 다중 기기 로그인+ 일부 속성 타입 TEXT로 변경
  src/main/java/com/influy/domain/announcement/entity/Announcement.java
  src/main/java/com/influy/domain/answer/entity/Answer.java
  src/main/java/com/influy/domain/item/entity/Item.java
  src/main/java/com/influy/domain/member/controller/MemberController.java
  src/main/java/com/influy/global/auth/service/AuthService.java
  src/main/java/com/influy/global/auth/service/KakaoAuthServiceImpl.java
  src/main/java/com/influy/global/redis/RedisService.java
Labels: ✨ Feature

#125 #64 refactor : inluyf 서비스만 재시작 되도록 설정
  .github/workflows/deploy.yml
Labels: 🌎 Deploy

#126 #64 Refactor: UTC로 타임존 설정
  Dockerfile
  src/main/java/com/influy/SpringbootApplication.java
Labels: 🛠️ Refactor

#132 #64 Refactor: top3 찜 개수 정렬, 인가 오류 해결
  src/main/java/com/influy/domain/admin/service/AdminServiceImpl.java
  src/main/java/com/influy/domain/home/service/HomeServiceImpl.java
  src/main/java/com/influy/domain/item/repository/ItemRepository.java
Labels: 🎨 Fix, 🛠️ Refactor

#133 Question 0개 시 카테고리 별 질문 개수 현황 오류 해결
  src/main/java/com/influy/domain/question/converter/QuestionConverter.java
  src/main/java/com/influy/domain/question/repository/QuestionRepository.java
  src/main/java/com/influy/domain/questionCategory/controller/QuestionCategoryController.java
  src/main/java/com/influy/domain/questionCategory/dto/jpql/CategoryJPQLResult.java
  src/main/java/com/influy/domain/questionCategory/service/QuestionCategoryService.java
  src/main/java/com/influy/domain/questionCategory/service/QuestionCategoryServiceImpl.java
Labels: 🎨 Fix

#135 #64 Refactor: 셀러 검색 찜 개수 추가
  src/main/java/com/influy/domain/faqCard/converter/FaqCardConverter.java
  src/main/java/com/influy/domain/like/repository/LikeRepository.java
  src/main/java/com/influy/domain/search/converter/SearchConverter.java
  src/main/java/com/influy/domain/search/dto/SearchResponseDto.java
  src/main/java/com/influy/domain/search/service/SearchServiceImpl.java
Labels: 🎨 Fix, 🛠️ Refactor

#137 #64 Refactor: 홈 정렬기준 수정
  src/main/java/com/influy/domain/item/repository/ItemRepository.java
Labels: 🛠️ Refactor
