Repository INFLUY/Influy-BE, pull requests merged in 2025-07, with the labels that each got.

#52 Feature: 아이템 카테고리 조회 api 구현 / Fix: Like 예약어 오류 해결
  src/main/java/com/influy/domain/category/controller/CategoryRestController.java
  src/main/java/com/influy/domain/category/converter/CategoryConverter.java
  src/main/java/com/influy/domain/category/dto/CategoryResponseDto.java
  src/main/java/com/influy/domain/category/repository/CategoryRepository.java
  src/main/java/com/influy/domain/category/service/CategoryService.java
  src/main/java/com/influy/domain/category/service/CategoryServiceImpl.java
  src/main/java/com/influy/domain/faqCard/converter/FaqCardConverter.java
  src/main/java/com/influy/domain/faqCard/dto/FaqCardRequestDto.java
  src/main/java/com/influy/domain/faqCard/dto/FaqCardResponseDto.java
  src/main/java/com/influy/domain/faqCard/service/FaqCardServiceImpl.java
  src/main/java/com/influy/domain/item/dto/ItemRequestDto.java
  src/main/java/com/influy/domain/item/service/ItemServiceImpl.java
  src/main/java/com/influy/domain/like/entity/Like.java
  src/main/java/com/influy/domain/member/entity/Member.java
  src/main/java/com/influy/domain/sellerProfile/service/SellerProfileServiceImpl.java
  src/main/resources/category-storage/category.json
Labels: 🎨 Fix, ✨ Feature

#55 #51 Fix: FAQ 카테고리 순서 관련 CRUD 수정
  src/main/java/com/influy/domain/faqCard/repository/FaqCardRepository.java
  src/main/java/com/influy/domain/faqCategory/controller/FaqRestController.java
  src/main/java/com/influy/domain/faqCategory/converter/FaqCategoryConverter.java
  src/main/java/com/influy/domain/faqCategory/dto/FaqCategoryRequestDto.java
  src/main/java/com/influy/domain/faqCategory/dto/FaqCategoryResponseDto.java
  src/main/java/com/influy/domain/faqCategory/entity/FaqCategory.java
  src/main/java/com/influy/domain/faqCategory/repository/FaqCategoryRepository.java
  src/main/java/com/influy/domain/faqCategory/service/FaqCategoryService.java
  src/main/java/com/influy/domain/faqCategory/service/FaqCategoryServiceImpl.java
Labels: 🎨 Fix

#69 #63 Feature: 톡박스 답변 관련 기능 구현
  src/main/java/com/influy/domain/ai/service/AiServiceImpl.java
  src/main/java/com/influy/domain/answer/controller/AnswerRestController.java
  src/main/java/com/influy/domain/answer/converter/AnswerConverter.java
  src/main/java/com/influy/domain/answer/dto/AnswerRequestDto.java
  src/main/java/com/influy/domain/answer/dto/AnswerResponseDto.java
  src/main/java/com/influy/domain/answer/entity/Answer.java
  src/main/java/com/influy/domain/answer/entity/AnswerType.java
  src/main/java/com/influy/domain/answer/repository/AnswerRepository.java
  src/main/java/com/influy/domain/answer/service/AnswerService.java
  src/main/java/com/influy/domain/answer/service/AnswerServiceImpl.java
  src/main/java/com/influy/domain/faqCard/controller/FaqCardRestController.java
  src/main/java/com/influy/domain/faqCard/converter/FaqCardConverter.java
  src/main/java/com/influy/domain/faqCard/dto/FaqCardResponseDto.java
  src/main/java/com/influy/domain/faqCard/entity/FaqCard.java
  src/main/java/com/influy/domain/faqCard/service/FaqCardService.java
  src/main/java/com/influy/domain/faqCard/service/FaqCardServiceImpl.java
  src/main/java/com/influy/domain/faqCategory/controller/FaqCategoryRestController.java
  src/main/java/com/influy/domain/faqCategory/service/FaqCategoryService.java
  src/main/java/com/influy/domain/faqCategory/service/FaqCategoryServiceImpl.java
  src/main/java/com/influy/domain/item/controller/ItemRestController.java
  src/main/java/com/influy/domain/item/converter/ItemConverter.java
  src/main/java/com/influy/domain/item/dto/ItemRequestDto.java
  src/main/java/com/influy/domain/item/dto/ItemResponseDto.java
  src/main/java/com/influy/domain/item/entity/Item.java
  src/main/java/com/influy/domain/item/service/ItemService.java
  src/main/java/com/influy/domain/item/service/ItemServiceImpl.java
  src/main/java/com/influy/domain/like/controller/LikeRestController.java
  src/main/java/com/influy/domain/member/service/MemberService.java
  src/main/java/com/influy/domain/member/service/MemberServiceImpl.java
  src/main/java/com/influy/domain/question/controller/QuestionController.java
  src/main/java/com/influy/domain/question/entity/Question.java
  src/main/java/com/influy/domain/question/repository/QuestionRepository.java
  src/main/java/com/influy/domain/question/service/QuestionService.java
  src/main/java/com/influy/domain/question/service/QuestionServiceImpl.java
  src/main/java/com/influy/domain/questionCategory/controller/QuestionCategoryController.java
  src/main/java/com/influy/domain/questionCategory/converter/QuestionCategoryConverter.java
  src/main/java/com/influy/domain/questionCategory/dto/QuestionCategoryResponseDto.java
  src/main/java/com/influy/domain/questionCategory/entity/QuestionCategory.java
  src/main/java/com/influy/domain/questionCategory/repository/QuestionCategoryRepository.java
  src/main/java/com/influy/domain/questionCategory/service/QuestionCategoryService.java
  src/main/java/com/influy/domain/questionCategory/service/QuestionCategoryServiceIml.java
  src/main/java/com/influy/domain/questionCategory/service/QuestionCategoryServiceImpl.java
  src/main/java/com/influy/domain/questionTag/entity/QuestionTag.java
  src/main/java/com/influy/domain/questionTag/repository/QuestionTagRepository.java
  src/main/java/com/influy/domain/sellerProfile/entity/SellerProfile.java
  src/main/java/com/influy/global/apiPayload/code/status/ErrorStatus.java
  src/main/resources/category-storage/question-category.json
Labels: ✨ Feature

#67 #66 질문 작성 + AI 소분류
  src/main/java/com/influy/domain/ai/converter/AiConverter.java
  src/main/java/com/influy/domain/ai/dto/AiRequestDTO.java
  src/main/java/com/influy/domain/ai/dto/AiResponseDTO.java
  src/main/java/com/influy/domain/ai/service/AiService.java
  src/main/java/com/influy/domain/ai/service/AiServiceImpl.java
  src/main/java/com/influy/domain/member/controller/MemberController.java
  src/main/java/com/influy/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/influy/domain/member/service/MemberServiceImpl.java
  src/main/java/com/influy/domain/question/controller/QuestionController.java
  src/main/java/com/influy/domain/question/converter/QuestionConverter.java
  src/main/java/com/influy/domain/question/dto/JPQLQuestionDTO.java
  src/main/java/com/influy/domain/question/dto/QuestionRequestDTO.java
  src/main/java/com/influy/domain/question/dto/QuestionResponseDTO.java
  src/main/java/com/influy/domain/question/dto/jpql/JPQLResult.java
  src/main/java/com/influy/domain/question/entity/Question.java
  src/main/java/com/influy/domain/question/repository/QuestionRepository.java
  src/main/java/com/influy/domain/question/service/QuestionService.java
  src/main/java/com/influy/domain/question/service/QuestionServiceImpl.java
  src/main/java/com/influy/domain/questionCategory/converter/QuestionCategoryConverter.java
  src/main/java/com/influy/domain/questionCategory/repository/QuestionCategoryRepository.java
  src/main/java/com/influy/domain/questionTag/converter/QuestionTagConverter.java
  src/main/java/com/influy/domain/questionTag/dto/QuestionTagResponseDTO.java
  src/main/java/com/influy/domain/questionTag/repository/QuestionTagRepository.java
  src/main/java/com/influy/domain/questionTag/service/QuestionTagService.java
  src/main/java/com/influy/domain/questionTag/service/QuestionTagServiceImpl.java
  src/main/java/com/influy/domain/sellerProfile/controller/SellerProfileController.java
  src/main/java/com/influy/domain/sellerProfile/service/SellerProfileServiceImpl.java
  src/main/java/com/influy/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/influy/global/auth/controller/AuthController.java
  src/main/java/com/influy/global/auth/converter/AuthConverter.java
  src/main/java/com/influy/global/auth/dto/AuthResponseDTO.java
  src/main/java/com/influy/global/auth/service/AuthService.java
  src/main/java/com/influy/global/auth/service/KakaoAuthServiceImpl.java
  src/main/java/com/influy/global/util/StaticValues.java
  src/main/resources/category-storage/aiQuestionCategory/prompt-question-category.txt
  src/main/resources/category-storage/aiQuestionClassification/system-prompt.txt
  src/main/resources/category-storage/question-category.json
Labels: ✨ Feature

#73 #64 Refactor: 대분류 ai 생성에서 저장 로직 수정
  src/main/java/com/influy/domain/ai/service/AiService.java
  src/main/java/com/influy/domain/ai/service/AiServiceImpl.java
  src/main/java/com/influy/domain/questionCategory/controller/QuestionCategoryController.java
  src/main/java/com/influy/domain/questionCategory/converter/QuestionCategoryConverter.java
  src/main/java/com/influy/domain/questionCategory/dto/QuestionCategoryRequestDto.java
  src/main/java/com/influy/domain/questionCategory/dto/QuestionCategoryResponseDto.java
  src/main/java/com/influy/domain/questionCategory/repository/QuestionCategoryRepository.java
  src/main/java/com/influy/domain/questionCategory/service/QuestionCategoryService.java
  src/main/java/com/influy/domain/questionCategory/service/QuestionCategoryServiceImpl.java
  src/main/java/com/influy/global/apiPayload/code/status/ErrorStatus.java
  src/main/resources/category-storage/question-category.json
Labels: ✨ Feature, 🛠️ Refactor

#82 #64 fix : shouldNotFilter+permitAll 경로 수정
  src/main/java/com/influy/domain/question/controller/QuestionController.java
  src/main/java/com/influy/domain/question/repository/QuestionRepository.java
  src/main/java/com/influy/global/config/SecurityConfig.java
  src/main/java/com/influy/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/influy/global/util/StaticValues.java
Labels: 🎨 Fix

#83 #64 Refactor: userDetails 처리 관리
  src/main/java/com/influy/domain/faqCard/converter/FaqCardConverter.java
  src/main/java/com/influy/domain/image/controller/ImageRestController.java
  src/main/java/com/influy/domain/image/service/ImageService.java
  src/main/java/com/influy/domain/image/service/ImageServiceImpl.java
  src/main/java/com/influy/domain/item/converter/ItemConverter.java
  src/main/java/com/influy/domain/item/repository/ItemRepository.java
  src/main/java/com/influy/domain/item/service/ItemServiceImpl.java
  src/main/java/com/influy/domain/like/converter/LikeConverter.java
  src/main/java/com/influy/domain/question/converter/QuestionConverter.java
  src/main/java/com/influy/domain/questionCategory/controller/QuestionCategoryController.java
  src/main/java/com/influy/domain/questionCategory/repository/QuestionCategoryRepository.java
  src/main/java/com/influy/domain/questionCategory/service/QuestionCategoryService.java
  src/main/java/com/influy/domain/questionCategory/service/QuestionCategoryServiceImpl.java
  src/main/java/com/influy/domain/search/service/SearchServiceImpl.java
  src/main/java/com/influy/global/config/SecurityConfig.java
  src/main/java/com/influy/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/influy/global/util/StaticValues.java
Labels: ✨ Feature, 🛠️ Refactor

#86 #75 seller 홈 아이템별 질문 현황 api 구현
  src/main/java/com/influy/domain/item/controller/ItemRestController.java
  src/main/java/com/influy/domain/item/converter/ItemConverter.java
  src/main/java/com/influy/domain/item/dto/ItemResponseDto.java
  src/main/java/com/influy/domain/item/dto/jpql/ItemJPQLResponse.java
  src/main/java/com/influy/domain/item/repository/ItemRepository.java
  src/main/java/com/influy/domain/item/service/ItemService.java
  src/main/java/com/influy/domain/item/service/ItemServiceImpl.java
  src/main/java/com/influy/domain/member/controller/MemberController.java
  src/main/java/com/influy/domain/questionCategory/dto/jpql/CategoryJPQLResult.java
  src/main/java/com/influy/domain/questionCategory/repository/QuestionCategoryRepository.java
  src/main/java/com/influy/domain/sellerProfile/controller/SellerProfileController.java
  src/main/java/com/influy/domain/sellerProfile/converter/SellerProfileConverter.java
  src/main/java/com/influy/domain/sellerProfile/service/SellerProfileService.java
  src/main/java/com/influy/domain/sellerProfile/service/SellerProfileServiceImpl.java
  src/main/java/com/influy/global/auth/service/AuthService.java
  src/main/java/com/influy/global/auth/service/KakaoAuthServiceImpl.java
Labels: ✨ Feature

#88 #66 Question get 리팩터링
  src/main/java/com/influy/domain/question/converter/QuestionConverter.java
  src/main/java/com/influy/domain/question/dto/QuestionResponseDTO.java
  src/main/java/com/influy/domain/question/dto/jpql/QuestionJPQLResult.java
  src/main/java/com/influy/domain/question/repository/QuestionRepository.java
  src/main/java/com/influy/domain/question/service/QuestionServiceImpl.java
  src/main/java/com/influy/domain/questionCategory/controller/QuestionCategoryController.java
  src/main/java/com/influy/domain/questionCategory/converter/QuestionCategoryConverter.java
  src/main/java/com/influy/domain/questionCategory/dto/QuestionCategoryResponseDto.java
  src/main/java/com/influy/domain/questionCategory/dto/jpql/CategoryJPQLResult.java
  src/main/java/com/influy/domain/questionCategory/repository/QuestionCategoryRepository.java
  src/main/java/com/influy/domain/questionCategory/service/QuestionCategoryService.java
  src/main/java/com/influy/domain/questionCategory/service/QuestionCategoryServiceImpl.java
  src/main/java/com/influy/domain/questionTag/repository/QuestionTagRepository.java
Labels: 🛠️ Refactor

#91 #64 Refactor: 홈/찜 관련 응답 필드 추가 및 수정
  src/main/java/com/influy/domain/item/converter/ItemConverter.java
  src/main/java/com/influy/domain/item/dto/ItemResponseDto.java
  src/main/java/com/influy/domain/like/converter/LikeConverter.java
  src/main/java/com/influy/domain/like/dto/LikeResponseDto.java
Labels: 🛠️ Refactor

#93 #64 Refactor: 아이템, 톡박스 관련 응답 필드 수정
  src/main/java/com/influy/domain/item/converter/ItemConverter.java
  src/main/java/com/influy/domain/item/dto/ItemResponseDto.java
  src/main/java/com/influy/domain/item/service/ItemServiceImpl.java
  src/main/java/com/influy/domain/question/converter/QuestionConverter.java
  src/main/java/com/influy/domain/question/dto/QuestionResponseDTO.java
Labels: 🛠️ Refactor

#95 #64 Feature: 홈 셀러 추천 구현 / Refactor: home 관련 기능 homeController로 이동
  src/main/java/com/influy/domain/home/controller/HomeRestController.java
  src/main/java/com/influy/domain/home/converter/HomeConverter.java
  src/main/java/com/influy/domain/home/dto/HomeResponseDto.java
  src/main/java/com/influy/domain/home/service/HomeService.java
  src/main/java/com/influy/domain/home/service/HomeServiceImpl.java
  src/main/java/com/influy/domain/item/controller/ItemRestController.java
  src/main/java/com/influy/domain/item/converter/ItemConverter.java
  src/main/java/com/influy/domain/item/dto/ItemResponseDto.java
  src/main/java/com/influy/domain/item/repository/ItemRepository.java
  src/main/java/com/influy/domain/item/service/ItemService.java
  src/main/java/com/influy/domain/item/service/ItemServiceImpl.java
  src/main/java/com/influy/domain/search/controller/SearchRestController.java
  src/main/java/com/influy/domain/search/service/SearchService.java
  src/main/java/com/influy/domain/search/service/SearchServiceImpl.java
  src/main/java/com/influy/domain/sellerProfile/repository/SellerProfileRepository.java
  src/main/java/com/influy/global/util/StaticValues.java
Labels: ✨ Feature, 🛠️ Refactor

#96 #61 feat : 셀러 페이지 방문 시 상품 없는 경우 null 대신 0으로 제공
  src/main/java/com/influy/domain/sellerProfile/converter/SellerProfileConverter.java
Labels: 🛠️ Refactor
